language: node_js
sudo: false

node_js:
  - "0.10"
  - "0.12"
  - "4"

script:
  - cake test
  - cake lint

before_install:
  - npm install "hubot@$HUBOT_VERSION" --save

cache:
  directories:
    - node_modules
